import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import db from '@models/index'
import start from '@lib/first_start.js'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  try{
    await db.sequelize.authenticate()
    await start()
  }catch(e){
    console.error("PAS DE BDD")
  }
  

  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>Root layout</div>
        {children}
      </body>
    </html>
  );
}
